import { IntegrationConfig } from './types';

export const ciscoIosxeConfig: IntegrationConfig = {
  type: 'cisco-iosxe',
  displayName: 'Cisco IOS-XE',
  category: 'networking',
  description: 'Cisco network device monitoring via RESTCONF',
  documentationUrl: 'https://developer.cisco.com/docs/ios-xe/',
  dependencies: {
    apis: ['Cisco RESTCONF API'],
    notes: 'Requires RESTCONF enabled on device with privilege level 15',
  },
  sampleName: 'My Catalyst Switch',
  defaultPort: 443,
  sampleHost: '192.168.1.1',

  auth: {
    defaultMethod: 'basic',
    commonFields: [],
    methods: [
      {
        method: 'basic',
        label: 'Username/Password',
        fields: [
          {
            key: 'username',
            label: 'Username',
            type: 'text',
            placeholder: 'admin',
            required: true,
          },
          {
            key: 'password',
            label: 'Password',
            type: 'password',
            required: true,
          },
        ],
      },
    ],
    helpText: 'Use credentials with privilege level 15 or appropriate RBAC permissions. RESTCONF must be enabled on the device.',
  },

  widgets: [
    {
      type: 'cisco-device-overview',
      name: 'Device Overview',
      description: 'Hostname, model, serial, IOS-XE version, and uptime',
      metric: 'device-info',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Info Cards (Default)' },
        { value: 'compact', label: 'Compact List' },
        { value: 'metrics', label: 'Large Metrics' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Hostname', key: 'showHostname' },
            { label: 'Model', key: 'showModel' },
            { label: 'Serial Number', key: 'showSerial' },
            { label: 'IOS-XE Version', key: 'showVersion' },
            { label: 'Uptime', key: 'showUptime' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-interface-list',
      name: 'Interface List',
      description: 'Table of interfaces with status, speed, and traffic',
      metric: 'interfaces',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'Interface Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Status Filter',
          key: 'statusFilter',
          type: 'button-group',
          options: [
            { value: '', label: 'All' },
            { value: 'up', label: 'Up' },
            { value: 'down', label: 'Down' },
          ],
        },
        {
          label: 'Interface Search',
          key: 'search',
          type: 'text',
          placeholder: 'Search interfaces...',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Status', key: 'showStatus' },
            { label: 'Speed', key: 'showSpeed' },
            { label: 'In Bytes', key: 'showInBytes' },
            { label: 'Out Bytes', key: 'showOutBytes' },
            { label: 'Errors', key: 'showErrors' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-interface-count',
      name: 'Interface Count',
      description: 'Summary of interface counts (total, up, down)',
      metric: 'interfaces',
      defaultSize: { w: 3, h: 2 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'numbers', label: 'Large Numbers (Default)' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'bars', label: 'Status Bars' },
      ],
      filters: [
        {
          label: 'Metrics to Display',
          key: 'metrics',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Total', key: 'showTotal' },
            { label: 'Up', key: 'showUp' },
            { label: 'Down', key: 'showDown' },
          ],
        },
      ],
    },
    {
      type: 'cisco-resource-usage',
      name: 'Resource Usage',
      description: 'CPU and memory utilization with visual gauges',
      metric: 'resources',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'bars', label: 'Progress Bars (Default)' },
        { value: 'gauges', label: 'Circular Gauges' },
        { value: 'text', label: 'Text Only' },
      ],
      filters: [
        {
          label: 'Metrics to Display',
          key: 'metrics',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'CPU Usage', key: 'showCpu' },
            { label: 'Memory Usage', key: 'showMemory' },
          ],
        },
        {
          label: 'Warning Threshold (%)',
          key: 'warningThreshold',
          type: 'number',
          placeholder: '75',
        },
        {
          label: 'Critical Threshold (%)',
          key: 'criticalThreshold',
          type: 'number',
          placeholder: '90',
        },
      ],
    },
    {
      type: 'cisco-environment-status',
      name: 'Environment Status',
      description: 'Temperature sensors, fan status, and power supplies',
      metric: 'environment',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'list', label: 'Status List' },
        { value: 'compact', label: 'Compact View' },
      ],
      filters: [
        {
          label: 'Sensor Type Filter',
          key: 'sensorType',
          type: 'button-group',
          options: [
            { value: '', label: 'All' },
            { value: 'temperature', label: 'Temperature' },
            { value: 'fan', label: 'Fan' },
            { value: 'power', label: 'Power' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Temperature Sensors', key: 'showTemperature' },
            { label: 'Fan Status', key: 'showFans' },
            { label: 'Power Supplies', key: 'showPower' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-vlan-list',
      name: 'VLAN List',
      description: 'VLAN IDs, names, and status',
      metric: 'vlans',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'VLAN Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Status Filter',
          key: 'statusFilter',
          type: 'button-group',
          options: [
            { value: '', label: 'All' },
            { value: 'active', label: 'Active' },
            { value: 'suspended', label: 'Suspended' },
          ],
        },
        {
          label: 'VLAN Search',
          key: 'search',
          type: 'text',
          placeholder: 'Search VLANs...',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'VLAN ID', key: 'showId' },
            { label: 'Name', key: 'showName' },
            { label: 'Status', key: 'showStatus' },
            { label: 'Port Count', key: 'showPorts' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-poe-status',
      name: 'PoE Status',
      description: 'Power over Ethernet budget and per-port consumption',
      metric: 'poe',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'table', label: 'Port Table' },
        { value: 'bars', label: 'Power Bars' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Power Summary', key: 'showSummary' },
            { label: 'Per-Port Details', key: 'showPorts' },
          ],
        },
        {
          label: 'Port Filter',
          key: 'portFilter',
          type: 'button-group',
          options: [
            { value: '', label: 'All' },
            { value: 'delivering', label: 'Delivering' },
            { value: 'disabled', label: 'Disabled' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-spanning-tree',
      name: 'Spanning Tree Status',
      description: 'Root bridge, local priority, and port states',
      metric: 'spanning-tree',
      defaultSize: { w: 5, h: 3 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'table', label: 'Port State Table' },
        { value: 'compact', label: 'Compact View' },
      ],
      filters: [
        {
          label: 'VLAN/Instance',
          key: 'instanceId',
          type: 'text',
          placeholder: 'VLAN ID (e.g., 1)',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Root Bridge Info', key: 'showRootBridge' },
            { label: 'Local Priority', key: 'showLocalPriority' },
            { label: 'Port States', key: 'showPortStates' },
            { label: 'Topology Changes', key: 'showTopologyChanges' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-stack-status',
      name: 'Stack Status',
      description: 'Stack members, roles, priority, and state',
      metric: 'stack',
      defaultSize: { w: 5, h: 3 },
      minSize: { w: 4, h: 2 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'Member Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Switch Number', key: 'showSwitchNumber' },
            { label: 'Role', key: 'showRole' },
            { label: 'Priority', key: 'showPriority' },
            { label: 'State', key: 'showState' },
            { label: 'MAC Address', key: 'showMac' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cisco-port-grid',
      name: 'Port Grid',
      description: 'Visual grid of switch ports with status indicators',
      metric: 'interfaces',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'grid', label: 'Port Grid (Default)' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'text', label: 'Text Only' },
      ],
      filters: [
        {
          label: 'Port Status to Show',
          key: 'portStatus',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Ports Up', key: 'showPortsUp' },
            { label: 'Ports Down', key: 'showPortsDown' },
          ],
        },
        {
          label: 'Physical Ports Only',
          key: 'showPhysicalOnly',
          type: 'checkbox',
        },
        {
          label: 'Show Speed',
          key: 'showSpeed',
          type: 'checkbox',
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
  ],
};
