import { IntegrationConfig } from './types';

export const dockerConfig: IntegrationConfig = {
  type: 'docker',
  displayName: 'Docker',
  category: 'infrastructure',
  description: 'Container management and monitoring for Docker hosts',
  documentationUrl: 'https://docs.docker.com/engine/api/',
  dependencies: {
    apis: ['Docker Engine API'],
    notes: 'Requires Docker socket access or TCP API endpoint',
  },
  sampleName: 'My Docker Host',
  defaultPort: 2375,
  sampleHost: '192.168.1.100',

  auth: {
    defaultMethod: 'token',
    commonFields: [
      {
        key: 'socketPath',
        label: 'Socket Path (leave empty for TCP)',
        type: 'text',
        placeholder: '/var/run/docker.sock',
        helpText: 'Unix socket path, or leave empty to use TCP with host/port',
        colSpan: 2,
      },
    ],
    methods: [
      {
        method: 'token',
        label: 'Connection Settings',
        fields: [
          {
            key: 'caCert',
            label: 'CA Certificate (PEM)',
            type: 'password',
            placeholder: 'Optional: paste CA cert for TLS',
            colSpan: 2,
          },
          {
            key: 'clientCert',
            label: 'Client Certificate (PEM)',
            type: 'password',
            placeholder: 'Optional: paste client cert for TLS',
            colSpan: 2,
          },
          {
            key: 'clientKey',
            label: 'Client Key (PEM)',
            type: 'password',
            placeholder: 'Optional: paste client key for TLS',
            colSpan: 2,
          },
        ],
      },
    ],
  },

  widgets: [
    {
      type: 'docker-container-list',
      name: 'Container List',
      description: 'List of Docker containers with status and resource usage',
      metric: 'containers',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'running', label: 'Running' },
            { value: 'stopped', label: 'Stopped' },
            { value: 'paused', label: 'Paused' },
            { value: 'restarting', label: 'Restarting' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. nginx*, *db, app1,app2',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Status', key: 'showStatus' },
            { label: 'Image', key: 'showImage' },
            { label: 'Created', key: 'showCreated' },
            { label: 'Ports', key: 'showPorts' },
          ],
        },
        {
          label: 'Show Actions',
          key: 'showActions',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'docker-container-stats',
      name: 'Container Stats',
      description: 'Real-time resource usage for containers',
      metric: 'container-stats',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'bars', label: 'Usage Bars (Default)' },
        { value: 'cards', label: 'Stat Cards' },
        { value: 'table', label: 'Table' },
      ],
      filters: [
        {
          label: 'Container Filter',
          key: 'containerFilter',
          type: 'text',
          placeholder: 'e.g. nginx*, *db, app1,app2',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'running', label: 'Running Only' },
          ],
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '10',
        },
        {
          label: 'Metrics to Display',
          key: 'metrics',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'CPU Usage', key: 'showCpu' },
            { label: 'Memory Usage', key: 'showMemory' },
            { label: 'Network I/O', key: 'showNetwork' },
            { label: 'Block I/O', key: 'showBlockIo' },
          ],
        },
        {
          label: 'Warning Threshold (%)',
          key: 'warningThreshold',
          type: 'number',
          placeholder: '75',
        },
        {
          label: 'Critical Threshold (%)',
          key: 'criticalThreshold',
          type: 'number',
          placeholder: '90',
        },
      ],
    },
    {
      type: 'docker-system-overview',
      name: 'System Overview',
      description: 'Docker host system information and status',
      metric: 'system',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Info Cards (Default)' },
        { value: 'compact', label: 'Compact View' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Docker Version', key: 'showVersion' },
            { label: 'Container Count', key: 'showContainerCount' },
            { label: 'Image Count', key: 'showImageCount' },
            { label: 'CPU/Memory', key: 'showResources' },
            { label: 'Storage Driver', key: 'showStorageDriver' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'docker-disk-usage',
      name: 'Disk Usage',
      description: 'Docker disk space usage breakdown',
      metric: 'disk-usage',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'bars', label: 'Usage Bars (Default)' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'table', label: 'Table' },
      ],
      filters: [
        {
          label: 'Categories to Display',
          key: 'categories',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Images', key: 'showImages' },
            { label: 'Containers', key: 'showContainers' },
            { label: 'Volumes', key: 'showVolumes' },
            { label: 'Build Cache', key: 'showBuildCache' },
          ],
        },
        {
          label: 'Show Reclaimable',
          key: 'showReclaimable',
          type: 'checkbox',
        },
        {
          label: 'Warning Threshold (GB)',
          key: 'warningThreshold',
          type: 'number',
          placeholder: '50',
        },
      ],
    },
    {
      type: 'docker-image-list',
      name: 'Image List',
      description: 'List of Docker images',
      metric: 'images',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. nginx*, ubuntu:*, *:latest',
        },
        {
          label: 'Show Dangling',
          key: 'showDangling',
          type: 'checkbox',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Tag', key: 'showTag' },
            { label: 'Size', key: 'showSize' },
            { label: 'Created', key: 'showCreated' },
            { label: 'ID', key: 'showId' },
          ],
        },
        {
          label: 'Sort By',
          key: 'sortBy',
          type: 'select',
          options: [
            { value: 'created', label: 'Created Date' },
            { value: 'size', label: 'Size' },
            { value: 'name', label: 'Name' },
          ],
        },
      ],
    },
    {
      type: 'docker-network-overview',
      name: 'Network Overview',
      description: 'Docker networks and their containers',
      metric: 'networks',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Driver',
          key: 'driver',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'bridge', label: 'Bridge' },
            { value: 'host', label: 'Host' },
            { value: 'overlay', label: 'Overlay' },
            { value: 'macvlan', label: 'Macvlan' },
            { value: 'none', label: 'None' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. bridge*, *net, app-network',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Driver', key: 'showDriver' },
            { label: 'Subnet', key: 'showSubnet' },
            { label: 'Gateway', key: 'showGateway' },
            { label: 'Containers', key: 'showContainers' },
          ],
        },
        {
          label: 'Show Built-in Networks',
          key: 'showBuiltin',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'docker-volume-list',
      name: 'Volume List',
      description: 'Docker volumes and their usage',
      metric: 'volumes',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Driver',
          key: 'driver',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'local', label: 'Local' },
            { value: 'nfs', label: 'NFS' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. data*, *-vol, app-data',
        },
        {
          label: 'Show Dangling',
          key: 'showDangling',
          type: 'checkbox',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Driver', key: 'showDriver' },
            { label: 'Mount Point', key: 'showMountPoint' },
            { label: 'Created', key: 'showCreated' },
            { label: 'Labels', key: 'showLabels' },
          ],
        },
      ],
    },
    {
      type: 'docker-container-logs',
      name: 'Container Logs',
      description: 'Live log viewer for a specific container',
      metric: 'containers',
      defaultSize: { w: 6, h: 5 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Container',
          key: 'containerId',
          type: 'text',
          placeholder: 'Container ID or name',
        },
        {
          label: 'Tail Lines',
          key: 'tailLines',
          type: 'number',
          placeholder: '100',
        },
        {
          label: 'Show Timestamps',
          key: 'showTimestamps',
          type: 'checkbox',
        },
        {
          label: 'Log Stream',
          key: 'stream',
          type: 'select',
          options: [
            { value: '', label: 'Both (stdout + stderr)' },
            { value: 'stdout', label: 'stdout only' },
            { value: 'stderr', label: 'stderr only' },
          ],
        },
        {
          label: 'Filter Pattern',
          key: 'filterPattern',
          type: 'text',
          placeholder: 'e.g. error, warning, INFO',
        },
      ],
    },
  ],
};
