import { IntegrationConfig } from './types';

export const giteaConfig: IntegrationConfig = {
  type: 'gitea',
  displayName: 'Gitea',
  category: 'utilities',
  description: 'Self-hosted Git service with issues, pull requests, and CI/CD',
  documentationUrl: 'https://docs.gitea.com/development/api-usage',
  dependencies: {
    apis: ['Gitea REST API v1'],
    notes: 'Requires API token with appropriate scopes. Create tokens in Settings > Applications.',
  },
  sampleName: 'My Gitea',
  defaultPort: 3000,
  sampleHost: 'gitea.example.com',

  auth: {
    defaultMethod: 'token',
    commonFields: [
      {
        key: 'host',
        label: 'Host',
        type: 'text',
        placeholder: 'gitea.example.com',
        required: true,
        helpText: 'Gitea server hostname (without protocol). Use https:// prefix to force HTTPS.',
      },
      {
        key: 'port',
        label: 'Port',
        type: 'number',
        placeholder: '3000',
        required: false,
        helpText: 'Leave empty for default. Port 443 automatically uses HTTPS.',
      },
    ],
    methods: [
      {
        method: 'token',
        label: 'API Token',
        fields: [
          {
            key: 'token',
            label: 'API Token',
            type: 'password',
            placeholder: 'Your Gitea API token',
            required: true,
            colSpan: 2,
            helpText: 'Generate in User Settings > Applications > Generate New Token',
          },
        ],
      },
      {
        method: 'basic',
        label: 'Username & Password',
        fields: [
          {
            key: 'username',
            label: 'Username',
            type: 'text',
            required: true,
          },
          {
            key: 'password',
            label: 'Password',
            type: 'password',
            required: true,
          },
          {
            key: 'otp',
            label: '2FA Code (if enabled)',
            type: 'text',
            required: false,
            helpText: 'Required if two-factor authentication is enabled',
          },
        ],
      },
    ],
    helpText: 'Generate API tokens in Gitea: User Settings > Applications > Access Tokens',
  },

  widgets: [
    {
      type: 'gitea-overview',
      name: 'Overview',
      description: 'Account summary with repository and organization counts',
      metric: 'overview',
      defaultSize: { w: 3, h: 2 },
      minSize: { w: 2, h: 2 },
      supportsMetricSize: true,
      supportsHideLabels: true,
      filters: [
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Repo Count', key: 'showRepoCount' },
            { label: 'Show Org Count', key: 'showOrgCount' },
            { label: 'Show Star Count', key: 'showStarCount' },
            { label: 'Show Follower Count', key: 'showFollowerCount' },
          ],
        },
      ],
    },
    {
      type: 'gitea-repositories',
      name: 'Repositories',
      description: 'List of repositories with stars, forks, and activity',
      metric: 'repositories',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Visibility',
          key: 'visibility',
          type: 'button-group',
          options: [
            { value: '', label: 'All' },
            { value: 'public', label: 'Public' },
            { value: 'private', label: 'Private' },
          ],
        },
        {
          label: 'Sort By',
          key: 'sortBy',
          type: 'button-group',
          options: [
            { value: 'updated', label: 'Updated' },
            { value: 'stars', label: 'Stars' },
            { value: 'forks', label: 'Forks' },
            { value: 'name', label: 'Name' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'Filter repositories',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Stars', key: 'showStars' },
            { label: 'Show Forks', key: 'showForks' },
            { label: 'Show Language', key: 'showLanguage' },
            { label: 'Show Description', key: 'showDescription' },
            { label: 'Show Last Updated', key: 'showLastUpdated' },
            { label: 'Show Visibility Badge', key: 'showVisibility' },
          ],
        },
      ],
    },
    {
      type: 'gitea-issues',
      name: 'Issues',
      description: 'Issues with status, labels, and assignees',
      metric: 'issues',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Repository',
          key: 'repository',
          type: 'text',
          placeholder: 'owner/repo (blank for all)',
        },
        {
          label: 'State',
          key: 'state',
          type: 'button-group',
          options: [
            { value: 'open', label: 'Open' },
            { value: 'closed', label: 'Closed' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          label: 'Labels',
          key: 'labels',
          type: 'text',
          placeholder: 'bug,enhancement',
        },
        {
          label: 'Sort By',
          key: 'sortBy',
          type: 'button-group',
          options: [
            { value: 'created', label: 'Newest' },
            { value: 'updated', label: 'Updated' },
            { value: 'comments', label: 'Comments' },
          ],
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Labels', key: 'showLabels' },
            { label: 'Show Assignee', key: 'showAssignee' },
            { label: 'Show Comments Count', key: 'showComments' },
            { label: 'Show Repository', key: 'showRepo' },
            { label: 'Show Milestone', key: 'showMilestone' },
          ],
        },
      ],
    },
    {
      type: 'gitea-pull-requests',
      name: 'Pull Requests',
      description: 'Pull requests with review and merge status',
      metric: 'pull-requests',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Repository',
          key: 'repository',
          type: 'text',
          placeholder: 'owner/repo (blank for all)',
        },
        {
          label: 'State',
          key: 'state',
          type: 'button-group',
          options: [
            { value: 'open', label: 'Open' },
            { value: 'closed', label: 'Closed' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          label: 'Sort By',
          key: 'sortBy',
          type: 'button-group',
          options: [
            { value: 'created', label: 'Newest' },
            { value: 'updated', label: 'Updated' },
          ],
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Author', key: 'showAuthor' },
            { label: 'Show Labels', key: 'showLabels' },
            { label: 'Show Branch Names', key: 'showBranches' },
            { label: 'Show Merge Status', key: 'showMergeStatus' },
            { label: 'Show Repository', key: 'showRepo' },
            { label: 'Show Changes', key: 'showChanges' },
          ],
        },
      ],
    },
    {
      type: 'gitea-activity',
      name: 'Activity',
      description: 'Contribution heatmap showing activity over time',
      metric: 'activity',
      defaultSize: { w: 6, h: 2 },
      minSize: { w: 4, h: 2 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Time Range',
          key: 'timeRange',
          type: 'button-group',
          options: [
            { value: 'year', label: 'Year' },
            { value: '6months', label: '6 Months' },
            { value: '3months', label: '3 Months' },
            { value: 'month', label: 'Month' },
          ],
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Total Count', key: 'showTotal' },
            { label: 'Show Day Labels', key: 'showDayLabels' },
            { label: 'Show Month Labels', key: 'showMonthLabels' },
          ],
        },
      ],
    },
    {
      type: 'gitea-organizations',
      name: 'Organizations',
      description: 'Organizations and team memberships',
      metric: 'organizations',
      defaultSize: { w: 3, h: 3 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Show Teams',
          key: 'showTeams',
          type: 'checkbox',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Member Count', key: 'showMemberCount' },
            { label: 'Show Repo Count', key: 'showRepoCount' },
            { label: 'Show Description', key: 'showDescription' },
          ],
        },
      ],
    },
    {
      type: 'gitea-notifications',
      name: 'Notifications',
      description: 'Notification inbox with unread indicators',
      metric: 'notifications',
      defaultSize: { w: 3, h: 4 },
      minSize: { w: 2, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Status',
          key: 'status',
          type: 'button-group',
          options: [
            { value: 'unread', label: 'Unread' },
            { value: 'all', label: 'All' },
            { value: 'pinned', label: 'Pinned' },
          ],
        },
        {
          label: 'Subject Type',
          key: 'subjectType',
          type: 'button-group',
          options: [
            { value: '', label: 'All' },
            { value: 'Issue', label: 'Issues' },
            { value: 'Pull', label: 'PRs' },
            { value: 'Commit', label: 'Commits' },
          ],
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Repository', key: 'showRepo' },
            { label: 'Show Timestamp', key: 'showTimestamp' },
            { label: 'Show Type Icon', key: 'showTypeIcon' },
          ],
        },
      ],
    },
  ],
};
