import { IntegrationConfig } from './types';

export const githubConfig: IntegrationConfig = {
  type: 'github',
  displayName: 'GitHub',
  category: 'utilities',
  description: 'Software development platform with version control, issues, PRs, and CI/CD',
  documentationUrl: 'https://docs.github.com/en/rest',
  dependencies: {
    apis: ['REST API v3', 'GraphQL API v4'],
    notes: 'GraphQL required for contribution graph data',
  },
  sampleName: 'My GitHub Account',
  defaultPort: 443,
  sampleHost: 'api.github.com',

  auth: {
    defaultMethod: 'token',
    commonFields: [],
    methods: [
      {
        method: 'token',
        label: 'Personal Access Token',
        fields: [
          {
            key: 'token',
            label: 'Personal Access Token',
            type: 'password',
            placeholder: 'ghp_... or github_pat_...',
            required: true,
            colSpan: 2,
            helpText: 'Create at github.com/settings/tokens. Required scopes: repo, read:user, notifications.',
          },
          {
            key: 'username',
            label: 'Username (Optional)',
            type: 'text',
            placeholder: 'your-username',
            required: false,
            colSpan: 1,
            helpText: 'Default username for user-scoped queries.',
          },
          {
            key: 'defaultOrg',
            label: 'Default Organization (Optional)',
            type: 'text',
            placeholder: 'your-org',
            required: false,
            colSpan: 1,
            helpText: 'Default organization for org-scoped queries.',
          },
        ],
      },
    ],
  },

  widgets: [
    {
      type: 'github-profile',
      name: 'Profile',
      description: 'User profile and quick stats',
      metric: 'user-profile',
      defaultSize: { w: 3, h: 2 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      filters: [
        {
          label: 'Username Override',
          key: 'username',
          type: 'text',
          placeholder: 'Leave empty for authenticated user',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Avatar', key: 'showAvatar' },
            { label: 'Show Repo Count', key: 'showRepoCount' },
            { label: 'Show Followers', key: 'showFollowers' },
            { label: 'Show Following', key: 'showFollowing' },
            { label: 'Show Bio', key: 'showBio' },
          ],
        },
      ],
    },
    {
      type: 'github-repo-stats',
      name: 'Repository Stats',
      description: 'Stars, forks, issues, and PR counts for a repository',
      metric: 'repository-stats',
      defaultSize: { w: 3, h: 2 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      filters: [
        {
          label: 'Repository',
          key: 'repo',
          type: 'text',
          placeholder: 'owner/repo',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Stars', key: 'showStars' },
            { label: 'Show Forks', key: 'showForks' },
            { label: 'Show Open Issues', key: 'showIssues' },
            { label: 'Show Open PRs', key: 'showPRs' },
            { label: 'Show Watchers', key: 'showWatchers' },
            { label: 'Show Language', key: 'showLanguage' },
            { label: 'Show Last Updated', key: 'showLastUpdated' },
          ],
        },
      ],
    },
    {
      type: 'github-repos',
      name: 'Repositories',
      description: 'List of repositories with key metrics',
      metric: 'repositories',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Owner',
          key: 'owner',
          type: 'text',
          placeholder: 'username or org (leave empty for authenticated user)',
        },
        {
          label: 'Type',
          key: 'type',
          type: 'button-group',
          options: [
            { value: 'all', label: 'All' },
            { value: 'owner', label: 'Owned' },
            { value: 'member', label: 'Member' },
          ],
        },
        {
          label: 'Visibility',
          key: 'visibility',
          type: 'button-group',
          options: [
            { value: 'all', label: 'All' },
            { value: 'public', label: 'Public' },
            { value: 'private', label: 'Private' },
          ],
        },
        {
          label: 'Sort By',
          key: 'sortBy',
          type: 'button-group',
          options: [
            { value: 'updated', label: 'Updated' },
            { value: 'pushed', label: 'Pushed' },
            { value: 'stars', label: 'Stars' },
            { value: 'name', label: 'Name' },
          ],
        },
        {
          label: 'Max Repos',
          key: 'maxItems',
          type: 'number',
          placeholder: '10',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Stars', key: 'showStars' },
            { label: 'Show Language', key: 'showLanguage' },
            { label: 'Show Description', key: 'showDescription' },
            { label: 'Show Last Updated', key: 'showLastUpdated' },
            { label: 'Show Visibility Badge', key: 'showVisibility' },
          ],
        },
      ],
    },
    {
      type: 'github-issues',
      name: 'Issues',
      description: 'Open and recent issues',
      metric: 'issues',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Repository',
          key: 'repo',
          type: 'text',
          placeholder: 'owner/repo (leave empty for all assigned)',
        },
        {
          label: 'State',
          key: 'state',
          type: 'button-group',
          options: [
            { value: 'open', label: 'Open' },
            { value: 'closed', label: 'Closed' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          label: 'Filter',
          key: 'filter',
          type: 'button-group',
          options: [
            { value: 'assigned', label: 'Assigned' },
            { value: 'created', label: 'Created' },
            { value: 'mentioned', label: 'Mentioned' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          label: 'Labels',
          key: 'labels',
          type: 'text',
          placeholder: 'bug,enhancement (comma-separated)',
        },
        {
          label: 'Max Issues',
          key: 'maxItems',
          type: 'number',
          placeholder: '15',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Labels', key: 'showLabels' },
            { label: 'Show Assignee', key: 'showAssignee' },
            { label: 'Show Comments Count', key: 'showComments' },
            { label: 'Show Repository', key: 'showRepo' },
            { label: 'Show Milestone', key: 'showMilestone' },
          ],
        },
      ],
    },
    {
      type: 'github-prs',
      name: 'Pull Requests',
      description: 'Pull requests with review status',
      metric: 'pull-requests',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Repository',
          key: 'repo',
          type: 'text',
          placeholder: 'owner/repo (leave empty for all)',
        },
        {
          label: 'State',
          key: 'state',
          type: 'button-group',
          options: [
            { value: 'open', label: 'Open' },
            { value: 'closed', label: 'Closed' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          label: 'Filter',
          key: 'filter',
          type: 'button-group',
          options: [
            { value: 'assigned', label: 'Assigned' },
            { value: 'created', label: 'Created' },
            { value: 'review-requested', label: 'Review Requested' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          label: 'Max PRs',
          key: 'maxItems',
          type: 'number',
          placeholder: '15',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Author', key: 'showAuthor' },
            { label: 'Show Labels', key: 'showLabels' },
            { label: 'Show Review Status', key: 'showReviewStatus' },
            { label: 'Show CI Status', key: 'showCIStatus' },
            { label: 'Show Repository', key: 'showRepo' },
            { label: 'Show Draft Badge', key: 'showDraft' },
          ],
        },
      ],
    },
    {
      type: 'github-actions',
      name: 'Actions',
      description: 'GitHub Actions workflow status',
      metric: 'actions-status',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Repository',
          key: 'repo',
          type: 'text',
          placeholder: 'owner/repo',
        },
        {
          label: 'Workflow',
          key: 'workflowId',
          type: 'text',
          placeholder: 'workflow-name.yml (leave empty for all)',
        },
        {
          label: 'Branch',
          key: 'branch',
          type: 'text',
          placeholder: 'main (leave empty for all)',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'button-group',
          options: [
            { value: 'all', label: 'All' },
            { value: 'success', label: 'Success' },
            { value: 'failure', label: 'Failure' },
            { value: 'in_progress', label: 'Running' },
          ],
        },
        {
          label: 'Max Runs',
          key: 'maxItems',
          type: 'number',
          placeholder: '10',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Workflow Name', key: 'showWorkflow' },
            { label: 'Show Branch', key: 'showBranch' },
            { label: 'Show Duration', key: 'showDuration' },
            { label: 'Show Trigger', key: 'showTrigger' },
            { label: 'Show Actor', key: 'showActor' },
          ],
        },
      ],
    },
    {
      type: 'github-notifications',
      name: 'Notifications',
      description: 'GitHub notification inbox',
      metric: 'notifications',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Filter',
          key: 'filter',
          type: 'button-group',
          options: [
            { value: 'unread', label: 'Unread' },
            { value: 'all', label: 'All' },
            { value: 'participating', label: 'Participating' },
          ],
        },
        {
          label: 'Repository',
          key: 'repo',
          type: 'text',
          placeholder: 'owner/repo (leave empty for all)',
        },
        {
          label: 'Max Notifications',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Repository', key: 'showRepo' },
            { label: 'Show Reason', key: 'showReason' },
            { label: 'Show Timestamp', key: 'showTimestamp' },
            { label: 'Show Type Icon', key: 'showTypeIcon' },
          ],
        },
      ],
    },
    {
      type: 'github-contributions',
      name: 'Contributions',
      description: 'Contribution activity heatmap',
      metric: 'contributions',
      defaultSize: { w: 6, h: 2 },
      minSize: { w: 4, h: 2 },
      supportsHideLabels: true,
      filters: [
        {
          label: 'Username',
          key: 'username',
          type: 'text',
          placeholder: 'Leave empty for authenticated user',
        },
        {
          label: 'Time Range',
          key: 'timeRange',
          type: 'button-group',
          options: [
            { value: 'year', label: 'Year' },
            { value: '6months', label: '6 Months' },
            { value: '3months', label: '3 Months' },
            { value: 'month', label: 'Month' },
          ],
        },
        {
          label: 'Display Options',
          key: 'displayOptions',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Total Count', key: 'showTotal' },
            { label: 'Show Day Labels', key: 'showDayLabels' },
            { label: 'Show Month Labels', key: 'showMonthLabels' },
            { label: 'Show Streak Info', key: 'showStreak' },
          ],
        },
      ],
    },
  ],
};
