import { IntegrationConfig } from './types';

export const proxmoxConfig: IntegrationConfig = {
  type: 'proxmox',
  displayName: 'Proxmox VE',
  category: 'infrastructure',
  description: 'Virtual machine and container management platform',
  documentationUrl: 'https://pve.proxmox.com/pve-docs/api-viewer/index.html',
  dependencies: {
    apis: ['Proxmox VE API'],
    notes: 'Requires API token or username/password authentication',
  },
  sampleName: 'My Proxmox Server',
  defaultPort: 8006,
  sampleHost: '192.168.1.100',

  auth: {
    defaultMethod: 'api',
    commonFields: [],
    methods: [
      {
        method: 'api',
        label: 'API Token',
        fields: [
          {
            key: 'tokenId',
            label: 'API Token ID',
            type: 'text',
            placeholder: 'user@pam!token-name',
            required: true,
            colSpan: 2,
          },
          {
            key: 'tokenSecret',
            label: 'API Token Secret',
            type: 'password',
            placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
            required: true,
            colSpan: 2,
          },
        ],
      },
      {
        method: 'basic',
        label: 'Username/Password',
        fields: [
          {
            key: 'username',
            label: 'Username',
            type: 'text',
            placeholder: 'root',
            required: true,
          },
          {
            key: 'realm',
            label: 'Realm',
            type: 'text',
            placeholder: 'pam',
            defaultValue: 'pam',
          },
          {
            key: 'password',
            label: 'Password',
            type: 'password',
            required: true,
            colSpan: 2,
          },
        ],
      },
    ],
  },

  widgets: [
    {
      type: 'guest-count',
      name: 'Guest Count',
      description: 'Running VMs and containers count',
      metric: 'guests',
      defaultSize: { w: 2, h: 2 },
      minSize: { w: 1, h: 1 },
      filters: [
        {
          label: 'Show Type',
          key: 'showType',
          type: 'select',
          options: [
            { value: 'both', label: 'VMs & Containers' },
            { value: 'vms', label: 'VMs Only' },
            { value: 'lxcs', label: 'Containers Only' },
          ],
        },
        {
          label: 'Show Stopped Count',
          key: 'showStopped',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'guest-list',
      name: 'Guest List',
      description: 'Combined list of VMs and LXC containers with resource usage',
      metric: 'guests',
      defaultSize: { w: 6, h: 5 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Guest Type',
          key: 'showType',
          type: 'select',
          options: [
            { value: '', label: 'All (VMs & Containers)' },
            { value: 'vms', label: 'VMs Only' },
            { value: 'lxcs', label: 'Containers Only' },
          ],
        },
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'running', label: 'Running' },
            { value: 'stopped', label: 'Stopped' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. web*, *server, 100,101',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '30',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Type (VM/LXC)', key: 'showTypeCol' },
            { label: 'Status', key: 'showStatus' },
            { label: 'CPU', key: 'showCpu' },
            { label: 'Memory', key: 'showMemory' },
            { label: 'Disk', key: 'showDisk' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Node', key: 'showNode' },
          ],
        },
      ],
    },
    {
      type: 'vm-list',
      name: 'VM List',
      description: 'List of QEMU virtual machines',
      metric: 'vms',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'running', label: 'Running' },
            { value: 'stopped', label: 'Stopped' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. web*, *server, vm1,vm2',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Status', key: 'showStatus' },
            { label: 'CPU', key: 'showCpu' },
            { label: 'Memory', key: 'showMemory' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Node', key: 'showNode' },
          ],
        },
      ],
    },
    {
      type: 'container-list',
      name: 'Container List',
      description: 'List of LXC containers',
      metric: 'containers',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'cards', label: 'Cards' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'running', label: 'Running' },
            { value: 'stopped', label: 'Stopped' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. ct*, *docker, ct1,ct2',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Status', key: 'showStatus' },
            { label: 'CPU', key: 'showCpu' },
            { label: 'Memory', key: 'showMemory' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Node', key: 'showNode' },
          ],
        },
      ],
    },
    {
      type: 'node-status',
      name: 'Node Status',
      description: 'Status of Proxmox nodes',
      metric: 'nodes',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Node Cards (Default)' },
        { value: 'list', label: 'Compact List' },
        { value: 'metrics', label: 'Large Metrics' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'online', label: 'Online Only' },
            { value: 'offline', label: 'Offline Only' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'CPU Usage', key: 'showCpu' },
            { label: 'Core Count', key: 'showCores' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Memory', key: 'showMemory' },
            { label: 'Storage', key: 'showStorage' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
        {
          label: 'Show Sparkline Trends',
          key: 'showSparklines',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'resource-usage',
      name: 'Resource Usage',
      description: 'CPU, RAM, and storage gauges',
      metric: 'nodes',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'bars', label: 'Horizontal Bars (Default)' },
        { value: 'gauges', label: 'Circular Gauges' },
        { value: 'text', label: 'Text Only' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Display Mode',
          key: 'displayMode',
          type: 'select',
          options: [
            { value: '', label: 'Aggregate (All Nodes)' },
            { value: 'individual', label: 'Individual Nodes' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'CPU', key: 'showCpu' },
            { label: 'Memory', key: 'showMemory' },
            { label: 'Storage', key: 'showStorage' },
            { label: 'Percentage Labels', key: 'showPercentage' },
          ],
        },
        {
          label: 'Warning Threshold (%)',
          key: 'warningThreshold',
          type: 'number',
          placeholder: '75',
        },
        {
          label: 'Critical Threshold (%)',
          key: 'criticalThreshold',
          type: 'number',
          placeholder: '90',
        },
        {
          label: 'Show Totals',
          key: 'totals',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Total Cores', key: 'showTotalCores' },
            { label: 'Total RAM', key: 'showTotalRam' },
            { label: 'Total Disk', key: 'showTotalDisk' },
          ],
        },
        {
          label: 'Show Sparkline Trends',
          key: 'showSparklines',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'storage-status',
      name: 'Storage Status',
      description: 'Storage pools and usage',
      metric: 'storage',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'bars', label: 'Usage Bars (Default)' },
        { value: 'table', label: 'Table View' },
        { value: 'donut', label: 'Donut Chart' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Storage Type',
          key: 'storageType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'dir', label: 'Directory' },
            { value: 'lvm', label: 'LVM' },
            { value: 'lvmthin', label: 'LVM-Thin' },
            { value: 'zfspool', label: 'ZFS Pool' },
            { value: 'nfs', label: 'NFS' },
            { value: 'cifs', label: 'CIFS' },
            { value: 'cephfs', label: 'CephFS' },
            { value: 'rbd', label: 'RBD' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Disabled', key: 'showDisabled' },
            { label: 'Inactive', key: 'showInactive' },
            { label: 'Usage Bar', key: 'showUsageBar' },
            { label: 'Type Column', key: 'showType' },
            { label: 'Content Column', key: 'showContent' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'task-list',
      name: 'Task List',
      description: 'Recent tasks and jobs',
      metric: 'tasks',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table (Default)' },
        { value: 'timeline', label: 'Timeline' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Task Type',
          key: 'taskType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'vncproxy', label: 'VNC Proxy' },
            { value: 'qmstart', label: 'VM Start' },
            { value: 'qmstop', label: 'VM Stop' },
            { value: 'qmmigrate', label: 'VM Migration' },
            { value: 'vzdump', label: 'Backup' },
            { value: 'vzrestore', label: 'Restore' },
            { value: 'download', label: 'Download' },
            { value: 'aptupdate', label: 'APT Update' },
          ],
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'running', label: 'Running' },
            { value: 'completed', label: 'Completed' },
            { value: 'failed', label: 'Failed' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. vzdum*, backup*, root,admin',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '15',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'User', key: 'showUser' },
            { label: 'Duration', key: 'showDuration' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'backup-status',
      name: 'Backup Status',
      description: 'Backup jobs and unprotected VMs',
      metric: 'backups',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'list', label: 'Backup List (Default)' },
        { value: 'cards', label: 'Job Cards' },
        { value: 'calendar', label: 'Schedule View' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'VM Type',
          key: 'vmType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'qemu', label: 'Virtual Machines' },
            { value: 'lxc', label: 'Containers' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Not Backed Up', key: 'showNotBackedUp' },
            { label: 'Backup Jobs', key: 'showJobs' },
            { label: 'Disabled Jobs', key: 'showDisabled' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'metrics-chart',
      name: 'Metrics Chart',
      description: 'Historical performance metrics',
      metric: 'rrddata',
      defaultSize: { w: 5, h: 5 },
      minSize: { w: 4, h: 4 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'sparklines', label: 'Mini Charts (Default)' },
        { value: 'line', label: 'Line Charts' },
        { value: 'area', label: 'Area Charts' },
      ],
      filters: [
        {
          label: 'Display Mode',
          key: 'displayMode',
          type: 'select',
          options: [
            { value: '', label: 'All Nodes (Combined)' },
            { value: 'individual', label: 'Individual Nodes' },
            { value: 'specific', label: 'Specific Node' },
          ],
        },
        {
          label: 'Node Name(s)',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'CPU Chart', key: 'showCpu' },
            { label: 'Memory Chart', key: 'showMemory' },
            { label: 'Network Chart', key: 'showNetwork' },
            { label: 'Disk I/O Chart', key: 'showDisk' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'cluster-status',
      name: 'Cluster Status',
      description: 'Cluster nodes and quorum status',
      metric: 'cluster-status',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'list', label: 'Node List' },
        { value: 'donut', label: 'Quorum Chart' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'online', label: 'Online Only' },
            { value: 'offline', label: 'Offline Only' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Cluster Info', key: 'showClusterInfo' },
            { label: 'Nodes', key: 'showNodes' },
            { label: 'Node Details', key: 'showNodeDetails' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'disk-status',
      name: 'Disk Status',
      description: 'Physical disk information and health',
      metric: 'disks',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Disk Table (Default)' },
        { value: 'cards', label: 'Disk Cards' },
        { value: 'list', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Disk Type',
          key: 'diskType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'ssd', label: 'SSD' },
            { value: 'hdd', label: 'HDD' },
            { value: 'nvme', label: 'NVMe' },
          ],
        },
        {
          label: 'Health Filter',
          key: 'healthFilter',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'healthy', label: 'Healthy Only' },
            { value: 'warning', label: 'Warning' },
            { value: 'failed', label: 'Failed' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. sda*, Samsung*, nvme0,sdb',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Health', key: 'showHealth' },
            { label: 'Wearout', key: 'showWearout' },
            { label: 'Model', key: 'showModel' },
            { label: 'Serial', key: 'showSerial' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'network-status',
      name: 'Network Interfaces',
      description: 'Network configuration and status',
      metric: 'network',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Interface Table (Default)' },
        { value: 'cards', label: 'Interface Cards' },
        { value: 'list', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Interface Type',
          key: 'interfaceType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'bridge', label: 'Bridge' },
            { value: 'bond', label: 'Bond' },
            { value: 'eth', label: 'Ethernet' },
            { value: 'vlan', label: 'VLAN' },
            { value: 'OVSBridge', label: 'OVS Bridge' },
          ],
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'active', label: 'Active Only' },
            { value: 'inactive', label: 'Inactive Only' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. vmbr*, eth*, 10.0.0.*',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Address', key: 'showAddress' },
            { label: 'Gateway', key: 'showGateway' },
            { label: 'Bridge Ports', key: 'showBridgePorts' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'ceph-status',
      name: 'Ceph Status',
      description: 'Ceph cluster health and capacity',
      metric: 'ceph',
      defaultSize: { w: 5, h: 5 },
      minSize: { w: 4, h: 4 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'gauges', label: 'Health Gauges' },
        { value: 'compact', label: 'Compact View' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'OSDs', key: 'showOSDs' },
            { label: 'Placement Groups', key: 'showPGs' },
            { label: 'Monitors', key: 'showMonitors' },
            { label: 'Capacity', key: 'showCapacity' },
            { label: 'Warnings', key: 'showWarnings' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'ha-status',
      name: 'HA Status',
      description: 'High Availability resources and status',
      metric: 'ha',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'list', label: 'Resource List (Default)' },
        { value: 'cards', label: 'Resource Cards' },
        { value: 'compact', label: 'Compact View' },
      ],
      filters: [
        {
          label: 'Node Filter',
          key: 'nodeFilter',
          type: 'text',
          placeholder: 'e.g. pve1, pve*, node1,node2',
        },
        {
          label: 'Resource Type',
          key: 'resourceType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'vm', label: 'Virtual Machines' },
            { value: 'ct', label: 'Containers' },
          ],
        },
        {
          label: 'State',
          key: 'state',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'started', label: 'Started' },
            { value: 'stopped', label: 'Stopped' },
            { value: 'error', label: 'Error' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Manager Status', key: 'showManagerStatus' },
            { label: 'Quorum', key: 'showQuorum' },
            { label: 'Resources', key: 'showResources' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
  ],
};
