import { IntegrationConfig } from './types';

export const unifiProtectConfig: IntegrationConfig = {
  type: 'unifi-protect',
  displayName: 'UniFi Protect',
  category: 'networking',
  description: 'Video surveillance and NVR system',
  documentationUrl: 'https://ubntwiki.com/products/software/unifi-protect/api',
  dependencies: {
    apis: ['UniFi Protect API'],
    notes: 'Requires API key from UniFi Console',
  },
  sampleName: 'My Protect NVR',
  defaultPort: 443,
  sampleHost: '192.168.1.1',

  auth: {
    defaultMethod: 'api',
    commonFields: [],
    methods: [
      {
        method: 'api',
        label: 'API Key',
        fields: [
          {
            key: 'apiKey',
            label: 'API Key',
            type: 'password',
            placeholder: 'Your UniFi Protect API Key',
            required: true,
            colSpan: 2,
            helpText: 'Generate from UniFi Console → Settings → System → API',
          },
        ],
      },
    ],
  },

  widgets: [
    {
      type: 'camera-list',
      name: 'Camera List',
      description: 'List of all cameras with status',
      metric: 'cameras',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'Camera Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'connected', label: 'Connected Only' },
            { value: 'disconnected', label: 'Disconnected Only' },
          ],
        },
        {
          label: 'Recording',
          key: 'recording',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'recording', label: 'Recording Only' },
            { value: 'not-recording', label: 'Not Recording' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. Front*, Garage, cam1,cam2',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Status', key: 'showStatus' },
            { label: 'Recording', key: 'showRecording' },
            { label: 'Motion', key: 'showMotion' },
            { label: 'Model', key: 'showModel' },
          ],
        },
      ],
    },
    {
      type: 'camera-count',
      name: 'Camera Count',
      description: 'Total and online camera count',
      metric: 'cameras',
      defaultSize: { w: 3, h: 2 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'numbers', label: 'Large Numbers (Default)' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'bars', label: 'Status Bars' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Online Count', key: 'showOnline' },
            { label: 'Recording Count', key: 'showRecording' },
          ],
        },
      ],
    },
    {
      type: 'sensor-list',
      name: 'Sensor List',
      description: 'Door/window, motion, and leak sensors',
      metric: 'sensors',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'Sensor Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Sensor Type',
          key: 'sensorType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'door', label: 'Door Sensors' },
            { value: 'window', label: 'Window Sensors' },
            { value: 'leak', label: 'Leak Sensors' },
            { value: 'motion', label: 'Motion Sensors' },
          ],
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'connected', label: 'Connected Only' },
            { value: 'disconnected', label: 'Disconnected Only' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. Front*, Garage, sensor1,sensor2',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Status', key: 'showStatus' },
            { label: 'Battery', key: 'showBattery' },
            { label: 'State (Open/Closed)', key: 'showState' },
            { label: 'Temperature', key: 'showTemperature' },
            { label: 'Humidity', key: 'showHumidity' },
          ],
        },
      ],
    },
    {
      type: 'nvr-status',
      name: 'NVR Status',
      description: 'NVR info, storage, and recording status',
      metric: 'nvr',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'compact', label: 'Compact View' },
        { value: 'metrics', label: 'Large Metrics' },
      ],
      filters: [
        {
          label: 'Storage Visualization',
          key: 'storageVisualization',
          type: 'button-group',
          options: [
            { value: 'bar', label: 'Bar' },
            { value: 'donut', label: 'Donut' },
            { value: 'number', label: 'Number' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'NVR Name', key: 'showName' },
            { label: 'Storage Usage', key: 'showStorage' },
            { label: 'Recording Status', key: 'showRecording' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Version', key: 'showVersion' },
            { label: 'Retention Period', key: 'showRetention' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'event-list',
      name: 'Recent Events',
      description: 'Motion and detection events',
      metric: 'events',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'list', label: 'Event List (Default)' },
        { value: 'timeline', label: 'Timeline' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Event Type',
          key: 'eventType',
          type: 'select',
          options: [
            { value: '', label: 'All Events' },
            { value: 'motion', label: 'Motion Only' },
            { value: 'smartDetectZone', label: 'Smart Detections' },
            { value: 'ring', label: 'Doorbell Rings' },
            { value: 'sensorMotion', label: 'Sensor Motion' },
            { value: 'sensorOpened', label: 'Door/Window Opened' },
          ],
        },
        {
          label: 'Max Events',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Event Time', key: 'showTime' },
            { label: 'Camera/Sensor Name', key: 'showDevice' },
            { label: 'Detection Types', key: 'showDetectionTypes' },
          ],
        },
      ],
    },
    {
      type: 'smart-detections',
      name: 'Smart Detections',
      description: 'AI detection counts (person, vehicle, etc.)',
      metric: 'smart-detections',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'numbers', label: 'Numbers (Default)' },
        { value: 'bars', label: 'Horizontal Bars' },
        { value: 'donut', label: 'Donut Chart' },
      ],
      filters: [
        {
          label: 'Detection Types to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Person', key: 'showPerson' },
            { label: 'Vehicle', key: 'showVehicle' },
            { label: 'Package', key: 'showPackage' },
            { label: 'Animal', key: 'showAnimal' },
            { label: 'Face', key: 'showFace' },
            { label: 'License Plate', key: 'showLicensePlate' },
          ],
        },
        {
          label: 'Time Range Label',
          key: 'showTimeRange',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'camera-snapshot',
      name: 'Camera Snapshot',
      description: 'Live snapshot from a single camera',
      metric: 'cameras',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'full', label: 'Full Image (Default)' },
        { value: 'fit', label: 'Fit to Widget' },
        { value: 'cover', label: 'Cover Widget' },
      ],
      filters: [
        {
          label: 'Camera',
          key: 'cameraId',
          type: 'camera-select',
        },
        {
          label: 'Refresh Interval (seconds)',
          key: 'snapshotRefreshInterval',
          type: 'number',
          placeholder: '30',
        },
        {
          label: 'Image Fit',
          key: 'objectFit',
          type: 'button-group',
          options: [
            { value: 'contain', label: 'Contain' },
            { value: 'cover', label: 'Cover' },
            { value: 'fill', label: 'Fill' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Camera Name', key: 'showCameraName' },
            { label: 'Timestamp', key: 'showTimestamp' },
          ],
        },
      ],
    },
  ],
};
