import { IntegrationConfig } from './types';

export const unifiConfig: IntegrationConfig = {
  type: 'unifi',
  displayName: 'UniFi Controller',
  category: 'networking',
  description: 'Ubiquiti network device management and monitoring',
  documentationUrl: 'https://ubntwiki.com/products/software/unifi-controller/api',
  dependencies: {
    apis: ['UniFi Controller API'],
    notes: 'API key or username/password authentication',
  },
  sampleName: 'My UniFi Controller',
  defaultPort: 443,
  sampleHost: '192.168.1.1',

  auth: {
    defaultMethod: 'api',
    commonFields: [
      {
        key: 'host',
        label: 'Host',
        type: 'text',
        placeholder: '192.168.1.1',
        required: true,
      },
      {
        key: 'port',
        label: 'Port',
        type: 'number',
        placeholder: '443',
        required: true,
      },
      {
        key: 'site',
        label: 'Site',
        type: 'text',
        placeholder: 'default',
        defaultValue: 'default',
        colSpan: 2,
      },
    ],
    methods: [
      {
        method: 'api',
        label: 'API Key',
        fields: [
          {
            key: 'apiKey',
            label: 'API Key',
            type: 'password',
            placeholder: 'Your UniFi API Key',
            required: true,
            colSpan: 2,
            helpText: 'Generate from UniFi Console → Settings → System → API',
          },
        ],
      },
      {
        method: 'basic',
        label: 'Username/Password',
        fields: [
          {
            key: 'username',
            label: 'Username',
            type: 'text',
            placeholder: 'admin',
            required: true,
          },
          {
            key: 'password',
            label: 'Password',
            type: 'password',
            required: true,
          },
        ],
      },
    ],
  },

  widgets: [
    {
      type: 'client-count',
      name: 'Client Count',
      description: 'Number of connected clients',
      metric: 'clients',
      defaultSize: { w: 3, h: 2 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'numbers', label: 'Numbers (Default)' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'text', label: 'Text Only' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Wired Count', key: 'showWired' },
            { label: 'Wireless Count', key: 'showWireless' },
          ],
        },
        {
          label: 'Large Display',
          key: 'largeDisplay',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'client-list',
      name: 'Client List',
      description: 'Detailed list of connected clients',
      metric: 'clients',
      defaultSize: { w: 6, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'Client Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Connection Type',
          key: 'connectionType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'wired', label: 'Wired Only' },
            { value: 'wireless', label: 'Wireless Only' },
          ],
        },
        {
          label: 'Search (name/IP/MAC)',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. server*, 192.168.*, name1,name2',
        },
        {
          label: 'Max Items',
          key: 'maxItems',
          type: 'number',
          placeholder: '20',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'IP Address', key: 'showIp' },
            { label: 'Type', key: 'showType' },
            { label: 'Traffic', key: 'showTraffic' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'MAC Address', key: 'showMac' },
          ],
        },
      ],
    },
    {
      type: 'network-health',
      name: 'Network Health',
      description: 'Overall network health status',
      metric: 'health',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Status Cards (Default)' },
        { value: 'indicators', label: 'Status Indicators' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Subsystems to Display',
          key: 'subsystems',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Internet (WWW)', key: 'showWww' },
            { label: 'WAN', key: 'showWan' },
            { label: 'LAN', key: 'showLan' },
            { label: 'WiFi (WLAN)', key: 'showWlan' },
            { label: 'VPN', key: 'showVpn' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'User Count', key: 'showUsers' },
            { label: 'Guest Count', key: 'showGuests' },
            { label: 'Throughput', key: 'showThroughput' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'active-devices',
      name: 'Active Devices',
      description: 'List of network devices',
      metric: 'devices',
      defaultSize: { w: 5, h: 4 },
      minSize: { w: 4, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'table', label: 'Table View (Default)' },
        { value: 'cards', label: 'Device Cards' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Device Type',
          key: 'deviceType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'uap', label: 'Access Points' },
            { value: 'usw', label: 'Switches' },
            { value: 'ugw', label: 'Gateways' },
            { value: 'udm', label: 'Dream Machines' },
          ],
        },
        {
          label: 'Status',
          key: 'status',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'online', label: 'Online Only' },
            { value: 'offline', label: 'Offline Only' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. switch*, AP-*, device1,device2',
        },
        {
          label: 'Columns to Display',
          key: 'columns',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Type', key: 'showType' },
            { label: 'Status', key: 'showStatus' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Model', key: 'showModel' },
          ],
        },
      ],
    },
    {
      type: 'wifi-networks',
      name: 'WiFi Networks',
      description: 'List of SSIDs (requires password auth)',
      metric: 'wlans',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Network Cards (Default)' },
        { value: 'list', label: 'Network List' },
        { value: 'compact', label: 'Compact List' },
      ],
      filters: [
        {
          label: 'Network Type',
          key: 'networkType',
          type: 'select',
          options: [
            { value: '', label: 'All' },
            { value: 'user', label: 'User Networks' },
            { value: 'guest', label: 'Guest Networks' },
          ],
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. Guest*, Home*, net1,net2',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Network Name', key: 'showName' },
            { label: 'Status Indicator', key: 'showStatus' },
            { label: 'Security Type', key: 'showSecurity' },
            { label: 'Client Count', key: 'showClients' },
            { label: 'Disabled Networks', key: 'showDisabled' },
          ],
        },
      ],
    },
    {
      type: 'dpi-stats',
      name: 'DPI Statistics',
      description: 'Traffic by category (requires password auth)',
      metric: 'dpi',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'bars', label: 'Horizontal Bars (Default)' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'text', label: 'Text Only' },
      ],
      filters: [
        {
          label: 'Max Categories',
          key: 'maxItems',
          type: 'number',
          placeholder: '8',
        },
        {
          label: 'Min Traffic (MB)',
          key: 'minTrafficMB',
          type: 'number',
          placeholder: '0',
        },
      ],
    },
    {
      type: 'events-list',
      name: 'Network Events',
      description: 'Recent events/alerts (requires password auth)',
      metric: 'events',
      defaultSize: { w: 4, h: 4 },
      minSize: { w: 3, h: 3 },
      supportsHideLabels: true,
      visualizations: [
        { value: 'list', label: 'List (Default)' },
        { value: 'timeline', label: 'Timeline' },
      ],
      filters: [
        {
          label: 'Subsystems to Display',
          key: 'subsystems',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'WiFi (WLAN)', key: 'showWlan' },
            { label: 'LAN', key: 'showLan' },
            { label: 'WAN', key: 'showWan' },
            { label: 'System', key: 'showSystem' },
          ],
        },
        {
          label: 'Max Events',
          key: 'maxItems',
          type: 'number',
          placeholder: '15',
        },
        {
          label: 'Search',
          key: 'search',
          type: 'text',
          placeholder: 'e.g. connect*, error*, wan,lan',
        },
      ],
    },
    {
      type: 'speed-test',
      name: 'Speed Test',
      description: 'Latest speed test results (requires password auth)',
      metric: 'speedtest',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'numbers', label: 'Large Numbers (Default)' },
        { value: 'gauges', label: 'Speed Gauges' },
        { value: 'bars', label: 'Speed Bars' },
      ],
      filters: [
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Download', key: 'showDownload' },
            { label: 'Upload', key: 'showUpload' },
            { label: 'Latency', key: 'showLatency' },
            { label: 'Test Date', key: 'showDate' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'wan-info',
      name: 'WAN Info',
      description: 'WAN IP addresses, gateway, and ISP info',
      metric: 'wan',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 3, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'cards', label: 'Info Cards (Default)' },
        { value: 'list', label: 'Info List' },
        { value: 'compact', label: 'Compact View' },
      ],
      filters: [
        {
          label: 'WAN Interface',
          key: 'wanInterface',
          type: 'select',
          options: [
            { value: '', label: 'All (WAN 1 & 2)' },
            { value: 'wan1', label: 'WAN 1 Only' },
            { value: 'wan2', label: 'WAN 2 Only' },
          ],
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'ISP Info', key: 'showIsp' },
            { label: 'Gateway Name', key: 'showGateway' },
            { label: 'Subnet Mask', key: 'showNetmask' },
            { label: 'Uptime', key: 'showUptime' },
            { label: 'Throughput', key: 'showThroughput' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
    {
      type: 'ap-status',
      name: 'Access Point Status',
      description: 'Display AP name, image, and connected client count',
      metric: 'devices',
      defaultSize: { w: 3, h: 4 },
      minSize: { w: 2, h: 3 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      filters: [
        {
          label: 'Access Point',
          key: 'deviceId',
          type: 'ap-select',
          placeholder: 'Select an access point...',
        },
        {
          label: 'Custom Image',
          key: 'customImageUrl',
          type: 'image-select',
        },
        {
          label: 'Elements to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'AP Name', key: 'showName' },
            { label: 'AP Image', key: 'showImage' },
            { label: 'Client Count', key: 'showClients' },
            { label: 'Status Indicator', key: 'showStatus' },
            { label: 'Model Name', key: 'showModel' },
          ],
        },
        {
          label: 'Image Size',
          key: 'imageSize',
          type: 'select',
          options: [
            { value: 'small', label: 'Small' },
            { value: 'medium', label: 'Medium' },
            { value: 'large', label: 'Large' },
          ],
        },
        {
          label: 'Client Count Size',
          key: 'clientCountSize',
          type: 'select',
          options: [
            { value: 'small', label: 'Small' },
            { value: 'medium', label: 'Medium' },
            { value: 'large', label: 'Large' },
            { value: 'extra-large', label: 'Extra Large' },
          ],
        },
      ],
    },
    {
      type: 'switch-ports',
      name: 'Switch Ports',
      description: 'Port status for UniFi switches (up/down count and visual grid)',
      metric: 'switch-ports',
      defaultSize: { w: 4, h: 3 },
      minSize: { w: 2, h: 2 },
      supportsHideLabels: true,
      supportsMetricSize: true,
      visualizations: [
        { value: 'default', label: 'Default View' },
        { value: 'donut', label: 'Donut Chart' },
        { value: 'text', label: 'Text Only' },
      ],
      filters: [
        {
          label: 'Select Switches',
          key: 'selectedSwitches',
          type: 'switch-select',
        },
        {
          label: 'Device Types to Include',
          key: 'deviceTypes',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Switches (USW)', key: 'showSwitches' },
            { label: 'Gateways (UDM)', key: 'showGateways' },
          ],
        },
        {
          label: 'Display Mode',
          key: 'displayMode',
          type: 'select',
          options: [
            { value: 'both', label: 'Numbers + Port Grid' },
            { value: 'numeric', label: 'Numbers Only' },
            { value: 'graphical', label: 'Port Grid Only' },
          ],
        },
        {
          label: 'Port Status to Display',
          key: 'displayElements',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Ports Up', key: 'showPortsUp' },
            { label: 'Ports Down', key: 'showPortsDown' },
          ],
        },
        {
          label: 'Port Details (Grid Mode)',
          key: 'portDetails',
          type: 'checkbox-group',
          defaultEnabled: true,
          items: [
            { label: 'Show Speed', key: 'showSpeed' },
            { label: 'Show PoE Indicator', key: 'showPoe' },
          ],
        },
        {
          label: 'Compact View',
          key: 'compactView',
          type: 'checkbox',
        },
      ],
    },
  ],
};
